modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="islam_mod_epic"
version="1.0.0"
displayName="islam mod epic"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="sexystilton, MCreator"

[[dependencies.islam_mod_epic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



